[tool.black]
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
      \.github
    | \.vscode
    | libsacn

    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''
