######## Configuration for MQTTany ########

# All optional values are commented out and default values are shown

### Notes on Topics:
#
# RELATIVE topics will have the 'root topic' and 'module topic' prepended.
#
# ABSOLUTE topics starting with '/' will be treated as absolute and will not
# have any other topics prepended.
#
# The following substitutions will be applied to all topics, modules may add
# more (see module for details)
# - {hostname} = the computer's hostname
# - {client_id} = the mqtt 'client id'
# - {root_topic} = the 'root topic'
# - {module_name} = the name of the module publishing or subscribing
# - {module_topic} = the main topic of the module pub-ing or sub-ing
###

######## MQTT Module ########
mqtt:

  ### Broker
  host:  # address or hostname
  #port: 1883

  ### User Data
  #client id: '{hostname}'
  #username:
  #password:

  ### Session Options
  #qos: 0
  #retain: false

  ### Topics
  #root topic: '{client_id}' # Root topic
  #lwt topic: 'lwt' # Last Will topic


######## GPIO Module ########
#gpio:

  ### Module Topic
  #topic: '{module_name}'

  ### Setter Topic
  # messages sent here will set a pin if it's configured as an output
  # default resolves to '{root_topic}/{module_name}/{pin}/set'
  #topic set: 'set'

  ### Getter Topic
  # any message here will cause pin state to be published
  # default resolves to '{root_topic}/{module_name}/{pin}/get'
  #topic get: 'get'

  ### Poll Topic
  # any message here will cause all pin states to be published
  # default resolves to '{root_topic}/{module_name}/poll'
  #topic poll: 'poll'

  ### ON Payload
  #payload on: 'ON' # message for pin ON

  ### OFF Payload
  #payload off: 'OFF' # message for pin OFF

  ### Polling Interval
  #polling interval: 0.0 # interval in seconds to poll all pins

  ### Interrupt Debounce
  #debounce: 200 # in milliseconds

  ### Single Pin Configuration
  #Single:

    ### Pin Number
    #pin:

    ### Pin Topic
    # Additional Subsitutions:
    # - {pin} = pin number
    # - {pin:02d} = pin number padded with 0's to always be 2 numbers
    # - {pin_name} = name of this section
    #topic: '{pin}'

    ### Pin Direction
    #direction: 'input' # can be 'input' or 'output'

    ### Pin Interrupt
    #interrupt: 'none' # can be 'rising', 'falling', 'both', or 'none'

    ### Pin Resistor
    #resistor: 'off' # can be 'pullup', 'pulldown', or 'off'

    ### Pin Invert
    # true means pin states ON=LOW, OFF=HIGH
    #invert: false # can be true or false

  ### Multiple Pin Configuration
  # alternatively a list of pins can be given
  # all options from a single pin configuration apply, except those shown below
  #Batch:

    ### Pin Numbers
    #pin: []

    ### Pin Topic
    # a single topic may be given, or a list of topics the same length as the
    # list of pins can be provided
    # Additional Subsitutions:
    # - {pin} = pin number
    # - {pin:02d} = pin number padded with 0's to always be 2 numbers
    # - {pin_name} = name of this section
    # - {index} = the pin's index in the list of pins plus 'first index'
    #topic: '{pin}'

    ### First Index
    # this number will be added to 'index' when substituting '{index}' in topics
    #first index: 0
