######## Configuration for MQTTany ########

# All optional values are commented out and default values are shown

### Notes on Topics:
#
# RELATIVE topics will have the 'root topic' and 'module topic' prepended.
#
# ABSOLUTE topics starting with '/' will be treated as absolute and will not
# have any other topics prepended.
#
# The following substitutions will be applied to all topics, modules may add
# more (see module for details)
# - {hostname} the computer's hostname
# - {client_id} the mqtt 'client id'
# - {root_topic} the 'root topic'
# - {module_name} the name of the module publishing or subscribing
# - {module_topic} the main topic of the module pub-ing or sub-ing
###

######## MQTT Module ########
mqtt:

  ### Broker
  host:  # address or hostname
  #port: 1883

  ### User Data
  #client id: '{hostname}'
  #username:
  #password:

  ### Session Options
  #qos: 0
  #retain: false

  ### Topics
  #root topic: '{client_id}' # Root topic
  #lwt topic: 'lwt' # Last Will topic


######## GPIO Module ########
#gpio:

  ### Module Topic
  #topic: '{module_name}'

  ### Setter Topic
  # messages sent here will set a pin if it's configured as an output
  # default resolves to '{root_topic}/{module_name}/{pin}/set'
  #topic set: 'set'

  ### Getter Topic
  # any message here will cause pin state to be published
  # default resolves to '{root_topic}/{module_name}/{pin}/get'
  #topic get: 'get'

  ### Poll Topic
  # any message here will cause all pin states to be published
  # default resolves to '{root_topic}/{module_name}/poll'
  #topic poll: 'poll'

  ### ON Payload
  #payload on: 'ON' # message for pin ON

  ### OFF Payload
  #payload off: 'OFF' # message for pin OFF

  ### Polling Interval
  #polling interval: 0.0 # interval in seconds to poll all pins

  ### Interrupt Debounce
  #debounce: 200 # in milliseconds

  ### Single Pin Configuration
  #Friendly Name:

    ### Pin Number
    #pin: 1

    ### Pin Topic
    # '{pin}' will be replaced with pin number
    #topic: '{pin}'

    ### Pin Direction
    #direction: 'input' # can be 'input' or 'output'

    ### Pin Interrupt
    #interrupt: 'none' # can be 'rising', 'falling', 'both', or 'none'

    ### Pin Resistor
    #resistor: 'off' # can be 'pullup', 'pulldown', or 'off'

    ### Pin Invert
    # true means pin states ON=LOW, OFF=HIGH
    #invert: false # can be true or false

  ### Multiple Pin Configuration
  # alternatively a list of pins can be given
  # all options from a single pin configuration apply, except those shown below
  #Batch:

    ### Pin Numbers
    #pin: [1, 2, 3]

    ### Pin Topic
    # '{pin}' will be replaced with pin number
    # '{index}' will be replaced by the pin's index in the list of pins plus 'first index'
    #topic: 'batch-{index}'
    # or a list of topics the same length as the list of pins can be provided
    #topic: ['one', 'two', 'three']

    ### First Index
    # this number will be added to 'index' when substituting '{index}' in topics
    #first index: 1



######## MCP230xx Module ########
#mcp230xx:

  ### Module Topic
  #topic: '{module_name}'

  ### Setter Topic
  # messages sent here will set a pin if it's configured as an output
  # default resolves to '{root_topic}/{module_name}/{bus_id}/{address:02x}/{pin}/set'
  #topic set: 'set'

  ### Getter Topic
  # any message here will cause pin state to be read published
  # default resolves to '{root_topic}/{module_name}/{bus_id}/{address:02x}/{pin}/get'
  #topic get: 'get'

  ### Poll Topic
  # any message here will cause all pin states to be published
  # default for all devices resolves to '{root_topic}/{module_name}/poll'
  # default for single device resolves to '{root_topic}/{module_name}/{bus_id}/{address:02x}/poll'
  #topic poll: 'poll'

  ### ON Payload
  #payload on: 'ON' # message for pin ON

  ### OFF Payload
  #payload off: 'OFF' # message for pin OFF

  ### Polling Interval
  #polling interval: 0.0 # interval in seconds to poll all pins

  ### Device Configuration
  #Friendly Name:

    ### I2C Bus ID
    # ID of the I2C bus to use on your SBC
    # ex. Raspberry Pi 3 this will probably be 1
    #bus id:

    ### Device Address
    # 7-bit hex address of the device (ex. 0x20)
    #address: 0x

    ### Device Type
    # Can be either 'MCP23017' or 'MCP23008'
    #device:

    ### Device Topic
    # Substitutions: {device_name} = Friendly name of device's section in config file
    #                {address:02x} = Device address in hex (ex. '20')
    #topic: '{device_name}'

    ### Pin Configurations
    # Refer to the GPIO Module pin configurations
    # The 'interrupt' option is not yet supported
