name: Code Style

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*
  pull_request:
    branches-ignore:
      - docs
      - gh-pages

jobs:
  black:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black \
                      -r requirements/mqttany.txt \
                      -r requirements/mqtt.txt \
                      -r requirements/i2c.txt \
                      -r requirements/led-rpi.txt \
                      -r requirements/led-sacn.txt

      - name: Checking code format with black
        run: |
          black --version
          black --check --verbose --diff --color ./mqttany
  # /black
  pyright:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/mqttany.txt \
                      -r requirements/mqtt.txt \
                      -r requirements/i2c.txt \
                      -r requirements/led-rpi.txt \
                      -r requirements/led-sacn.txt

      - name: Checking code with pyright
        uses: jakebailey/pyright-action@v2
  # /pyright
